#!/usr/bin/env python3
"""
Consumer DNA raw-data files: parsing, matching against known variants, importing.
All data here is made up; the rs numbers are public identifiers.
"""

import gzip
import os
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).parent.parent))

import config
import raw_dna
from app import app
from database_manager import GeneticProfileDB

TWENTYTHREE = """# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024
# ...reference human assembly build 37 (also known as Annotation Release 104)...
#
# rsid\tchromosome\tposition\tgenotype
rs4244285\t10\t96541616\tAG
rs9923231\t16\t31107689\tCT
rs1801133\t1\t11856378\tGG
rs0000001\t1\t100\t--
i3000001\tMT\t1\tA
"""

ANCESTRY = """#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 01/01/2024
#Data was collected using AncestryDNA array version: V2.0
#Genotype data is provided on reference build GRCh37
rsid\tchromosome\tposition\tallele1\tallele2
rs4244285\t10\t96541616\tA\tG
rs9923231\t16\t31107689\tT\tT
rs0000002\t23\t200\t0\t0
rs0000003\t26\t300\tC\tC
"""

MYHERITAGE = '''##fileformat=MyHeritage
# MyHeritage DNA raw data.
# For each SNP, we provide the identifier, chromosome number, base pair position and genotype.
RSID,CHROMOSOME,POSITION,RESULT
"rs4244285","10","96541616","AG"
"rs1801133","1","11856378","AA"
"rs0000004","2","400","--"
'''


def write(directory, name, text, mode='w'):
    path = Path(directory) / name
    with open(path, mode) as handle:
        handle.write(text)
    return path


class TestParse(unittest.TestCase):

    def setUp(self):
        self.dir = tempfile.mkdtemp()

    def test_23andme(self):
        parsed = raw_dna.parse(write(self.dir, 'genome.txt', TWENTYTHREE))
        self.assertEqual(parsed.provider, '23andme')
        self.assertEqual(parsed.build, '37')
        self.assertEqual([v.rsid for v in parsed.variants],
                         ['rs4244285', 'rs9923231', 'rs1801133', 'i3000001'])
        self.assertEqual(parsed.no_calls, 1)

    def test_ancestry_alleles_and_chromosome_codes(self):
        parsed = raw_dna.parse(write(self.dir, 'dna.txt', ANCESTRY))
        self.assertEqual(parsed.provider, 'ancestry')
        self.assertEqual(parsed.build, '37')
        by_rsid = {v.rsid: v for v in parsed.variants}
        self.assertEqual(by_rsid['rs4244285'].genotype, 'AG')
        self.assertEqual(by_rsid['rs0000003'].chromosome, 'MT')
        self.assertNotIn('rs0000002', by_rsid)
        self.assertEqual(parsed.no_calls, 1)

    def test_myheritage_csv(self):
        parsed = raw_dna.parse(write(self.dir, 'dna.csv', MYHERITAGE))
        self.assertEqual(parsed.provider, 'myheritage')
        self.assertEqual({v.rsid: v.genotype for v in parsed.variants},
                         {'rs4244285': 'AG', 'rs1801133': 'AA'})

    def test_zip_and_gzip(self):
        zip_path = Path(self.dir) / 'genome.zip'
        with zipfile.ZipFile(zip_path, 'w') as archive:
            archive.writestr('genome_v5.txt', TWENTYTHREE)
        self.assertEqual(len(raw_dna.parse(zip_path).variants), 4)
        gz_path = Path(self.dir) / 'genome.txt.gz'
        with gzip.open(gz_path, 'wt') as handle:
            handle.write(TWENTYTHREE)
        self.assertEqual(len(raw_dna.parse(gz_path).variants), 4)

    def test_not_raw_data(self):
        with self.assertRaises(raw_dna.UnreadableRawData):
            raw_dna.parse(write(self.dir, 'notes.txt', 'Dear doctor,\nthis is a letter.\n'))
        with self.assertRaises(raw_dna.UnreadableRawData):
            raw_dna.parse(write(self.dir, 'empty.txt', ''))


class TestImport(unittest.TestCase):

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.db_path = str(Path(self.dir) / 'test.db')
        self.db = GeneticProfileDB(self.db_path)
        self.db.add_gene('CYP2C19', 'Cytochrome P450 2C19', '10')
        self.db.add_gene('VKORC1', 'Vitamin K epoxide reductase', '16')
        self.sources_dir = Path(self.dir) / 'primary_sources'
        self.patch = mock.patch.object(config, 'PRIMARY_SOURCES_DIR', self.sources_dir)
        self.patch.start()

    def tearDown(self):
        self.patch.stop()
        self.db.close()

    def test_dry_run_reports_and_writes_nothing(self):
        path = write(self.dir, 'genome.txt', TWENTYTHREE)
        summary = raw_dna.import_file(self.db, path, dry_run=True)
        self.assertTrue(summary.dry_run)
        self.assertEqual(summary.variant_count, 4)
        self.assertEqual(summary.genes_in_ledger, ['CYP2C19', 'VKORC1'])
        self.assertEqual(summary.genes_not_in_ledger, ['MTHFR'])
        self.assertEqual(self.db.count_snp_genotypes(), 0)
        self.assertEqual(self.db.get_dna_imports(), [])
        self.assertFalse(self.sources_dir.exists())

    def test_import_writes_everything(self):
        path = write(self.dir, 'genome.txt', TWENTYTHREE)
        summary = raw_dna.import_file(self.db, path)
        self.assertIsNotNone(summary.import_id)
        self.assertEqual(self.db.count_snp_genotypes(), 4)
        self.assertEqual(self.db.get_snp_genotypes(['rs4244285', 'rs9923231', 'rs404']),
                         {'rs4244285': 'AG', 'rs9923231': 'CT'})
        imports = self.db.get_dna_imports()
        self.assertEqual(len(imports), 1)
        self.assertEqual(imports[0]['provider'], '23andMe')
        self.assertEqual(imports[0]['matched_count'], 2)
        self.assertTrue((self.sources_dir / 'dna' / 'genome.txt').exists())
        # The file shows up among the records
        sources = self.db.get_all_primary_sources() if hasattr(self.db, 'get_all_primary_sources') else None
        cursor = self.db.conn.cursor()
        cursor.execute("SELECT source_type, institution FROM primary_sources")
        self.assertEqual(cursor.fetchall()[0][:2], ('dna_raw_data', '23andMe'))
        # Matched variants exist in snps, linked to their gene
        gene = self.db.get_gene_by_symbol('CYP2C19')
        self.assertEqual([s['rs_number'] for s in self.db.get_snps_for_gene(gene['id'])], ['rs4244285'])

    def test_reimport_replaces_same_variants(self):
        raw_dna.import_file(self.db, write(self.dir, 'a.txt', TWENTYTHREE))
        raw_dna.import_file(self.db, write(self.dir, 'b.csv', MYHERITAGE))
        self.assertEqual(self.db.get_snp_genotypes(['rs1801133']), {'rs1801133': 'AA'})
        self.assertEqual(self.db.count_snp_genotypes(), 4)
        self.assertEqual(len(self.db.get_dna_imports()), 2)


class TestImportPage(unittest.TestCase):

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        db_path = str(Path(self.dir) / 'test.db')
        db = GeneticProfileDB(db_path)
        db.add_gene('CYP2C19', 'Cytochrome P450 2C19', '10')
        db.close()
        app.config['TESTING'] = True
        self.patches = [
            mock.patch.object(config, 'DB_PATH', Path(db_path)),
            mock.patch.object(config, 'DATA_ROOT', Path(self.dir)),
            mock.patch.object(config, 'PRIMARY_SOURCES_DIR', Path(self.dir) / 'primary_sources'),
        ]
        for p in self.patches:
            p.start()
        self.client = app.test_client()

    def tearDown(self):
        for p in self.patches:
            p.stop()

    def test_page_lists_providers(self):
        page = self.client.get('/import').get_data(as_text=True)
        self.assertIn('23andMe', page)
        self.assertIn('Read this file', page)

    def test_preview_then_confirm(self):
        response = self.client.post('/import/preview', data={
            'file': (open(write(self.dir, 'genome.txt', TWENTYTHREE), 'rb'), 'genome.txt')})
        self.assertEqual(response.status_code, 200)
        page = response.get_data(as_text=True)
        self.assertIn('Found 1 of your variants in 1 gene this ledger tracks', page)
        self.assertIn('CYP2C19', page)
        self.assertIn('MTHFR', page)
        token = page.split('name="token" value="')[1].split('"')[0]
        self.assertEqual(len(list((Path(self.dir) / 'imports').iterdir())), 1)
        self.assertEqual(GeneticProfileDB(config.DB_PATH).count_snp_genotypes(), 0)

        response = self.client.post('/import/dna', data={'token': token})
        self.assertEqual(response.status_code, 302)
        self.assertTrue(response.headers['Location'].endswith('/?notice=dna'))
        self.assertEqual(GeneticProfileDB(config.DB_PATH).count_snp_genotypes(), 4)
        self.assertEqual(list((Path(self.dir) / 'imports').iterdir()), [])
        page = self.client.get('/import').get_data(as_text=True)
        self.assertIn('Already in the ledger', page)

    def test_cancel_forgets_the_upload(self):
        page = self.client.post('/import/preview', data={
            'file': (open(write(self.dir, 'genome.txt', TWENTYTHREE), 'rb'), 'genome.txt')}).get_data(as_text=True)
        token = page.split('name="token" value="')[1].split('"')[0]
        response = self.client.post('/import/cancel', data={'token': token})
        self.assertEqual(response.status_code, 302)
        self.assertEqual(list((Path(self.dir) / 'imports').iterdir()), [])

    def test_bad_token_is_refused(self):
        self.assertEqual(self.client.post('/import/dna', data={'token': '../x'}).status_code, 400)

    def test_a_file_that_is_not_raw_data_falls_through_to_the_document_reader(self):
        # The page takes a file, not a file type: text that is not a DNA
        # download is offered as a document instead of being turned away.
        response = self.client.post('/import/preview', data={
            'file': (open(write(self.dir, 'letter.txt', 'Dear doctor, thank you for seeing this patient.'),
                          'rb'), 'letter.txt')})
        self.assertEqual(response.status_code, 200)
        self.assertIn('What the document holds', response.get_data(as_text=True))

    def test_a_zip_that_is_not_raw_data_says_so(self):
        # Only a DNA download arrives zipped, so the DNA message is the useful one.
        response = self.client.post('/import/preview', data={
            'file': (open(write(self.dir, 'photos.zip', 'not a zip'), 'rb'), 'photos.zip')})
        self.assertEqual(response.status_code, 400)
        self.assertIn('could not be opened', response.get_data(as_text=True))
        self.assertEqual(list((Path(self.dir) / 'imports').iterdir()), [])


if __name__ == '__main__':
    unittest.main()
